### ISSUE TITLE
100% CPU usage

### ISSUE THREAD

**Issue by c0d3st0rm** [liamg/shox#13]
Hi,

Using the install script, I've got the latest release of `shox` in `~/bin`, but when run it eats up one/two threads on a dual-core HT machine. I haven't let it run long or tested it otherwise. Any idea as to why this could be?

I'm running Debian 10, with Linux 5.5.0, zsh 5.7.1 with `oh-my-zsh`. Please let me know if you need any more information.

![image](https://user-images.githubusercontent.com/10127691/75451073-caf85f80-5967-11ea-8fa3-ab32e0a9a168.png)

**Comment by liamg** [comment]
This should be resolved in `v0.0.9`.  Was busy IO, which is now resolved with some backoff delay where no data is available.
